version: 0.0
os: linux

# Define your environment variables here (no need to specify values here)
env:
  DESTINATION_PATH: "/MyApp/DESTINATION_PATH"
  DOCUMENT_ROOT: "/MyApp/DOCUMENT_ROOT"
  SERVICE_NAME: "MyApp/SERVICE_NAME"

files:
  - source: /
    destination: "/home/ec2-user/${DESTINATION_PATH}"

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 500
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 500
      runas: root

