
# Retrieve the values from AWS Systems Manager Parameter Store
DESTINATION_PATH=$(aws ssm get-parameter --name "/MyApp/DESTINATION_PATH" --query "Parameter.Value" --output text)

version: 0.0
os: linux
files:
  - source: /
    destination: "/home/ec2-user/${DESTINATION_PATH}"


permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 500
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 500
      runas: root

