apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sharmaakshat37/reactfrontendimg:latest
          ports:
            - containerPort: 3000 
          env:
            - name: backendURL
              value: "http://backendconnect.com:2000"